const DATA = {
  "villes": [
    "agadir",
    "casablanca",
    "fes",
    "marrakech",
    "rabat",
    "tanger"
  ],
  "quartiers_par_ville": {
    "agadir": [
      "abattoirs",
      "agadir oufella",
      "al wifaq",
      "amicales",
      "amsernate",
      "anahda",
      "anza",
      "assaka",
      "ben serguaou",
      "bouargane",
      "boutchakat",
      "charaf",
      "cit adrar",
      "extension dakhla",
      "founti",
      "haut anza",
      "haut founty",
      "hay al farah",
      "hay dakhla",
      "hay hassani",
      "hay houda",
      "hay massira",
      "hay mohammadi",
      "hay najah",
      "hay qods",
      "hay salam",
      "hay zaytoun",
      "illigh",
      "lekhiam",
      "port",
      "riad salam",
      "secteur touristique",
      "siusse",
      "taddart",
      "taddart anza",
      "talborjt",
      "tikiouine",
      "tilila",
      "ville nouvelle",
      "zone industrielle agadir"
    ],
    "casablanca": [
      "ahl loghlam",
      "ain borja",
      "ain chock",
      "ain diab",
      "ain diab extension",
      "ain sebaa",
      "al andalous",
      "al azhar",
      "al farah dar essalam",
      "al hadika",
      "al hassania",
      "al madina aljadida",
      "al osra",
      "al qods",
      "almaz",
      "alsace lorraine",
      "anassi",
      "ancienne medina",
      "anfa",
      "anfa superieur",
      "beausite",
      "beausjour",
      "bel air",
      "belvdre",
      "benjdia",
      "bernoussi",
      "bouchentouf",
      "bourgogne est",
      "bourgogne ouest",
      "bournazil",
      "bouskoura ville",
      "burger",
      "californie",
      "casablanca finance city",
      "casablanca marina",
      "centre ville",
      "cil",
      "city dar es salaam",
      "dar bouazza",
      "dar lamane",
      "dar touzani",
      "derb al kabir",
      "derb al youssofia",
      "derb ben houmane",
      "derb carlotti",
      "derb chorfa",
      "derb douam",
      "derb el mitre",
      "derb espagnol",
      "derb friha",
      "derb ghalef",
      "derb khlifa",
      "derb kora",
      "derb lihoudi",
      "derb loubila",
      "derb milan",
      "derb moulay cherif",
      "derb omar",
      "derb salama",
      "el manar - el hank",
      "ferme bretonne",
      "foncire",
      "franceville",
      "garage allal",
      "gauthier",
      "habbous",
      "hay adil",
      "hay al amal",
      "hay al fadl",
      "hay al fath",
      "hay al kodia",
      "hay al othmania",
      "hay al qods",
      "hay alamal",
      "hay albaraka",
      "hay alfalah",
      "hay alfarah",
      "hay alfoqara",
      "hay alhoda",
      "hay almasjid",
      "hay almassira 2",
      "hay annour",
      "hay antaria",
      "hay arrahma",
      "hay arsalan",
      "hay chifa",
      "hay chrifa",
      "hay haddaouia",
      "hay hakam",
      "hay hassani",
      "hay idrissia",
      "hay inara",
      "hay lalla meriem",
      "hay layoune",
      "hay lmkansa",
      "hay m'barka",
      "hay mansour",
      "hay mohammadi",
      "hay moulay abdellah",
      "hay moulay rachid 1",
      "hay moulay rachid 4",
      "hay moulay rachid 6",
      "hay palestine",
      "hay rajaa",
      "hay sadri",
      "hay salama",
      "hay smara",
      "hay tarik",
      "hay tasahol",
      "hay zobir",
      "hermitage",
      "ifriquia",
      "inconnu",
      "itissal",
      "jamila 1",
      "jamila 2",
      "jamila 3",
      "jamila 4",
      "jamila 5",
      "jamila 7",
      "jawadi",
      "ksar lebhar",
      "la floride",
      "la gironde",
      "la vilette",
      "lahraouiyine",
      "laymoune",
      "lekrimat",
      "les crtes",
      "les hpitaux",
      "les princesses",
      "libert",
      "lissasfa",
      "longchamps",
      "lusitania",
      "mabroka",
      "mandarona",
      "marif",
      "marif extension",
      "massudia",
      "mers sultan",
      "miamar",
      "michouar",
      "moulay youssef",
      "nassim 1",
      "nassim 2",
      "nouaceur",
      "oasis",
      "oasis sud",
      "oulfa",
      "palmier",
      "plateau",
      "polo",
      "port",
      "quartier al woroud",
      "quartier bachkou",
      "quartier cheminots",
      "racine",
      "racine extension",
      "riad el ali",
      "riviera",
      "roches noires",
      "salmia 1",
      "salmia 2",
      "sidi belyout",
      "sidi el khadir",
      "sidi maarouf",
      "sidi marouf",
      "sidi moumen",
      "sidi othmane",
      "sour jdid",
      "tacharouk",
      "tantonville",
      "triangle d'or",
      "val fleury",
      "vermont",
      "yasmina",
      "zone industrielle",
      "zone industrielle moulay rachid",
      "zone industrielle oukacha"
    ],
    "fes": [
      "agdal",
      "ain amiyer",
      "ain haroun",
      "ain kadous",
      "ain noqbi",
      "al adarissa",
      "al farah",
      "al hadiqa",
      "al karaouiyine",
      "ancienne medina",
      "annouzha",
      "bab lghoul",
      "bad boujloud",
      "bourmana",
      "centre",
      "champ de course",
      "el keddan",
      "el mokhfia",
      "fes city center",
      "fes jdid",
      "hay ait skato",
      "hay al azhar",
      "hay al qods",
      "hay al wafaa",
      "hay al wifaq",
      "hay anas",
      "hay annassim",
      "hay atlas",
      "hay badr",
      "hay bassma",
      "hay bensouda",
      "hay dalia",
      "hay essalam",
      "hay fadela",
      "hay farah",
      "hay gryou",
      "hay hassani",
      "hay karim amrani",
      "hay lalla soukaina",
      "hay moulay el kamel",
      "hay najah",
      "hay nour",
      "hay riad",
      "hay tarik 1",
      "hay tarik 2",
      "hay zaza",
      "inconnu",
      "jnane eddar",
      "l'habitat",
      "laayoun",
      "lido",
      "mechouar",
      "mont fleuri",
      "narjis",
      "nouvelle ville",
      "oliverie",
      "oued fes",
      "qasbat ennouar",
      "quartier oued fes",
      "rahbet zbib",
      "riad",
      "route ain chkaf",
      "route de meknes",
      "route immouzer",
      "route se sefrou",
      "saada",
      "sehrij gnawa",
      "talaa",
      "tghat",
      "zekak erroumane",
      "zone industrielle ain chkef",
      "zouagha",
      "zouagha bas"
    ],
    "marrakech": [
      "agdal",
      "ain mezouar",
      "amelkis",
      "amerchich",
      "aouatif",
      "arset ben chebli",
      "arset el houta",
      "arset el maach",
      "arset ihiri",
      "arset moulay bouaazza",
      "arset moulay moussa",
      "arset sbaia",
      "assif",
      "assouel",
      "azli",
      "azzouzia",
      "bab aylan",
      "bab ghmat",
      "bab ighli",
      "bab lhmar",
      "belbekkar",
      "ben saleh",
      "berrima",
      "bouaakkaz",
      "boukar",
      "boulevard med 6",
      "boumesmar",
      "camp al ghoul",
      "daoudiat",
      "derb chtouka",
      "douar dlam",
      "el hara",
      "el moukef",
      "ennakhil",
      "essebtiyen",
      "gueliz",
      "hay al bahja",
      "hay al haouz",
      "hay al hassani",
      "hay al massar",
      "hay alfadl",
      "hay annahda",
      "hay chouhada",
      "hay firdaouss",
      "hay inara",
      "hay lalla haya",
      "hay mabrouka",
      "hay mohammadi",
      "hay saada",
      "hay saada 1",
      "hay targa",
      "hay yasmina",
      "hay zitoun",
      "hivernage",
      "inconnu",
      "issil",
      "izdihar",
      "iziki",
      "jawhar",
      "jbilat",
      "jnan ben chagra",
      "jnane laafia",
      "kaa el machraa",
      "kaat ben nahid",
      "kbour chou",
      "kechich",
      "kennaria",
      "koudia",
      "ksibat nhas",
      "les portes de marrakech",
      "majorelle",
      "masmoudi",
      "massira 1",
      "massira 2",
      "massira 3",
      "mdina",
      "mhamid",
      "michouar",
      "mouassine",
      "moulay lyazid",
      "ouasis",
      "rahba kedima",
      "riad al atlas",
      "riad zitoun",
      "rmila",
      "route amizmiz",
      "route casablanca",
      "route d'agadir - essaouira",
      "route de fez",
      "route de l'ourika",
      "route de ouarzazate",
      "route de safi",
      "route de tahanaout",
      "samlalia",
      "sanaoubar",
      "sidi abbad",
      "sidi ben slimane el jazouli",
      "sidi bou amar",
      "sidi ghanem",
      "sidi mansour",
      "sidi mimoun",
      "sidi youssef",
      "zaouia sidi ghalem",
      "zaouiat lahdar",
      "zone industrielle sidi ghanem"
    ],
    "rabat": [
      "agdal",
      "akkari",
      "al irfane",
      "al kamra",
      "al kouass",
      "al saha al kabira",
      "aviation - mabella",
      "bouitate",
      "diour jamaa",
      "el youssoufia",
      "guich oudaya",
      "harhoura",
      "hassan - centre ville",
      "haut agdal",
      "hay ach-chbanat",
      "hay al amal",
      "hay al barid",
      "hay al fath",
      "hay al kora",
      "hay al massira",
      "hay al rajaa fillah",
      "hay bouhlal",
      "hay el menzah",
      "hay nahda",
      "inconnu",
      "kbibat",
      "l'ocean",
      "les orangers",
      "les oudayas",
      "mdina",
      "mechouar",
      "quartier administratif",
      "quartier des ambassades",
      "riyad",
      "riyad extension",
      "skhirat",
      "souissi",
      "takadoum",
      "zone industrielle"
    ],
    "tanger": [
      "achakar",
      "achennad",
      "administratif",
      "ahammar",
      "aharrarine",
      "ahlane",
      "aida",
      "ain el hayani",
      "al amal",
      "al mandar al jamil",
      "aouama gharbia",
      "azib haj kaddour",
      "beausejour",
      "behair",
      "bel air - val fleuri",
      "bella vista",
      "ben dibane",
      "beni makada lakdima",
      "beni said",
      "beni touzine",
      "benkirane",
      "bir aharchoune",
      "bir chairi",
      "bir chifa",
      "bir el ghazi",
      "boukhalef",
      "branes 1",
      "branes 2",
      "branes kdima",
      "californie",
      "cap spartel",
      "casabarata",
      "castilla",
      "centre",
      "charf",
      "de la plage",
      "dher lahmam",
      "draoua",
      "drissia",
      "du golf",
      "el baraka",
      "el haj el mokhtar",
      "el majd",
      "el mers 1",
      "el mers 2",
      "el mrabet",
      "el oued",
      "ennasr",
      "gourziana",
      "haddad",
      "hanaa 1",
      "hanaa 2",
      "hanaa 3 - soussi",
      "hay al bassatine",
      "hay el boughaz",
      "hay hassani",
      "iberie",
      "inconnu",
      "jbel kbir",
      "jirrari",
      "laaouina",
      "lalla chafia",
      "les rosiers",
      "malabata",
      "manar",
      "marchan",
      "marjane",
      "mdina",
      "mediouna",
      "mesnana",
      "mghayer",
      "mghogha",
      "mister khouch",
      "moujahidine",
      "mozart",
      "msala",
      "nzaha",
      "port tanger ville",
      "rmilat",
      "route nationale assilah",
      "sania",
      "souani",
      "star hill",
      "tanger city center",
      "tanger medina",
      "tanja balia",
      "zemmouri",
      "ziaten",
      "zone industrielle mghogha",
      "zouitina"
    ]
  },
  "type_features": {
    "appartement": [
      "terrasse",
      "garage",
      "ascenseur",
      "piscine",
      "securite"
    ],
    "bureau": [
      "terrasse",
      "garage",
      "ascenseur",
      "securite"
    ],
    "ferme": [
      "garage",
      "securite"
    ],
    "local_commercial": [
      "garage",
      "ascenseur",
      "securite"
    ],
    "logement": [],
    "maison": [
      "terrasse",
      "garage",
      "piscine",
      "securite"
    ],
    "riad": [
      "terrasse",
      "garage",
      "piscine",
      "securite"
    ],
    "terrain": [],
    "villa": [
      "terrasse",
      "garage",
      "ascenseur",
      "piscine",
      "securite"
    ]
  },
  "types_sans_chambres": [],
  "types_avec_etage": [
    "appartement",
    "bureau",
    "ferme",
    "local_commercial",
    "logement",
    "maison",
    "riad",
    "terrain",
    "villa"
  ],
  "types_biens_disponibles": [
    "appartement",
    "bureau",
    "ferme",
    "local_commercial",
    "logement",
    "maison",
    "riad",
    "terrain",
    "villa"
  ]
};